[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sidereal_visibility_avg"
version = "0.2.0"
dependencies = []

[project.scripts]
sidereal_visibility_avg = "sidereal_visibility_avg.main:main"