[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sidereal_visibility_averaging"
version = "0.1.0"
dependencies = []

[project.scripts]
your-command = "sidereal_visibility_averaging.main:main"